import Head from "next/head";
import Footer from "./footer/footer";
import Header from "./header/header";

const Main = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <Header />
        <main>
            {children}
        </main>
      <Footer />
    </>
  );
};

export default Main;
